# Generated by Django 3.2.9 on 2021-11-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('field1', models.CharField(max_length=50, verbose_name='Поле1')),
                ('field2', models.TextField(verbose_name='Поле2')),
            ],
        ),
    ]
