# Generated by Django 3.2.9 on 2021-11-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualEnterpriseSurvey2019FinancialYearProvisionalCsv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.TextField(blank=True, null=True)),
                ('field2', models.TextField(blank=True, null=True)),
                ('field3', models.TextField(blank=True, null=True)),
                ('field4', models.TextField(blank=True, null=True)),
                ('field5', models.TextField(blank=True, null=True)),
                ('field6', models.TextField(blank=True, null=True)),
                ('field7', models.TextField(blank=True, null=True)),
                ('field8', models.TextField(blank=True, null=True)),
                ('field9', models.TextField(blank=True, null=True)),
                ('field10', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'annual-enterprise-survey-2019-financial-year-provisional-csv',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
