# Generated by Django 3.2.9 on 2021-11-29 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_csv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Datatest',
        ),
    ]
